// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bodyweight.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBodyweightLog = `-- name: CreateBodyweightLog :one
INSERT INTO bodyweight (
    user_id, date, kg
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, date, kg
`

type CreateBodyweightLogParams struct {
	UserID int64
	Date   pgtype.Date
	Kg     pgtype.Numeric
}

func (q *Queries) CreateBodyweightLog(ctx context.Context, arg CreateBodyweightLogParams) (Bodyweight, error) {
	row := q.db.QueryRow(ctx, createBodyweightLog, arg.UserID, arg.Date, arg.Kg)
	var i Bodyweight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Kg,
	)
	return i, err
}

const deleteBodyweightLog = `-- name: DeleteBodyweightLog :exec
DELETE FROM bodyweight WHERE id = $1 AND user_id = $2
`

type DeleteBodyweightLogParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteBodyweightLog(ctx context.Context, arg DeleteBodyweightLogParams) error {
	_, err := q.db.Exec(ctx, deleteBodyweightLog, arg.ID, arg.UserID)
	return err
}

const getBodyweightByDate = `-- name: GetBodyweightByDate :many
SELECT id, user_id, date, kg FROM bodyweight
WHERE user_id = $1 AND date = $2
ORDER BY id
`

type GetBodyweightByDateParams struct {
	UserID int64
	Date   pgtype.Date
}

func (q *Queries) GetBodyweightByDate(ctx context.Context, arg GetBodyweightByDateParams) ([]Bodyweight, error) {
	rows, err := q.db.Query(ctx, getBodyweightByDate, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bodyweight
	for rows.Next() {
		var i Bodyweight
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Kg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBodyweightByDateRange = `-- name: GetBodyweightByDateRange :many
SELECT id, user_id, date, kg FROM bodyweight
WHERE user_id = $1 AND date BETWEEN $2 AND $3
ORDER BY date
`

type GetBodyweightByDateRangeParams struct {
	UserID int64
	Date   pgtype.Date
	Date_2 pgtype.Date
}

func (q *Queries) GetBodyweightByDateRange(ctx context.Context, arg GetBodyweightByDateRangeParams) ([]Bodyweight, error) {
	rows, err := q.db.Query(ctx, getBodyweightByDateRange, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bodyweight
	for rows.Next() {
		var i Bodyweight
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Kg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBodyweightByID = `-- name: GetBodyweightByID :one
SELECT id, user_id, date, kg FROM bodyweight
WHERE id = $1 AND user_id = $2
`

type GetBodyweightByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetBodyweightByID(ctx context.Context, arg GetBodyweightByIDParams) (Bodyweight, error) {
	row := q.db.QueryRow(ctx, getBodyweightByID, arg.ID, arg.UserID)
	var i Bodyweight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Kg,
	)
	return i, err
}

const getLatestBodyweight = `-- name: GetLatestBodyweight :one
SELECT id, user_id, date, kg FROM bodyweight
WHERE user_id = $1
ORDER BY date DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestBodyweight(ctx context.Context, userID int64) (Bodyweight, error) {
	row := q.db.QueryRow(ctx, getLatestBodyweight, userID)
	var i Bodyweight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Kg,
	)
	return i, err
}
