// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCalorieLog = `-- name: CreateCalorieLog :one
INSERT INTO calories (
    user_id, date, kcal, description
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, date, kcal, description
`

type CreateCalorieLogParams struct {
	UserID      int64
	Date        pgtype.Date
	Kcal        int32
	Description pgtype.Text
}

func (q *Queries) CreateCalorieLog(ctx context.Context, arg CreateCalorieLogParams) (Calorie, error) {
	row := q.db.QueryRow(ctx, createCalorieLog,
		arg.UserID,
		arg.Date,
		arg.Kcal,
		arg.Description,
	)
	var i Calorie
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Kcal,
		&i.Description,
	)
	return i, err
}

const deleteCalorieLog = `-- name: DeleteCalorieLog :exec
DELETE FROM calories WHERE id = $1 AND user_id = $2
`

type DeleteCalorieLogParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteCalorieLog(ctx context.Context, arg DeleteCalorieLogParams) error {
	_, err := q.db.Exec(ctx, deleteCalorieLog, arg.ID, arg.UserID)
	return err
}

const getCalorieLogByID = `-- name: GetCalorieLogByID :one
SELECT id, user_id, date, kcal, description FROM calories
WHERE id = $1 AND user_id = $2
`

type GetCalorieLogByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetCalorieLogByID(ctx context.Context, arg GetCalorieLogByIDParams) (Calorie, error) {
	row := q.db.QueryRow(ctx, getCalorieLogByID, arg.ID, arg.UserID)
	var i Calorie
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Kcal,
		&i.Description,
	)
	return i, err
}

const getCaloriesByDate = `-- name: GetCaloriesByDate :many
SELECT id, user_id, date, kcal, description FROM calories
WHERE user_id = $1 AND date = $2
ORDER BY id
`

type GetCaloriesByDateParams struct {
	UserID int64
	Date   pgtype.Date
}

func (q *Queries) GetCaloriesByDate(ctx context.Context, arg GetCaloriesByDateParams) ([]Calorie, error) {
	rows, err := q.db.Query(ctx, getCaloriesByDate, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Calorie
	for rows.Next() {
		var i Calorie
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Kcal,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCaloriesByDateRange = `-- name: GetCaloriesByDateRange :many
SELECT id, user_id, date, kcal, description FROM calories
WHERE user_id = $1 AND date BETWEEN $2 AND $3
ORDER BY date
`

type GetCaloriesByDateRangeParams struct {
	UserID int64
	Date   pgtype.Date
	Date_2 pgtype.Date
}

func (q *Queries) GetCaloriesByDateRange(ctx context.Context, arg GetCaloriesByDateRangeParams) ([]Calorie, error) {
	rows, err := q.db.Query(ctx, getCaloriesByDateRange, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Calorie
	for rows.Next() {
		var i Calorie
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Kcal,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyCalorieTotal = `-- name: GetDailyCalorieTotal :one
SELECT COALESCE(SUM(kcal), 0)::int AS total_kcal
FROM calories
WHERE user_id = $1 AND date = $2
`

type GetDailyCalorieTotalParams struct {
	UserID int64
	Date   pgtype.Date
}

func (q *Queries) GetDailyCalorieTotal(ctx context.Context, arg GetDailyCalorieTotalParams) (int32, error) {
	row := q.db.QueryRow(ctx, getDailyCalorieTotal, arg.UserID, arg.Date)
	var total_kcal int32
	err := row.Scan(&total_kcal)
	return total_kcal, err
}

const getFrequentCalorieEntries = `-- name: GetFrequentCalorieEntries :many
SELECT description, kcal, COUNT(*) AS times_logged, MAX(date) AS last_logged
FROM calories
WHERE user_id = $1 AND description IS NOT NULL
GROUP BY description, kcal
ORDER BY times_logged DESC, last_logged DESC
LIMIT $2
`

type GetFrequentCalorieEntriesParams struct {
	UserID int64
	Limit  int32
}

type GetFrequentCalorieEntriesRow struct {
	Description pgtype.Text
	Kcal        int32
	TimesLogged int64
	LastLogged  interface{}
}

func (q *Queries) GetFrequentCalorieEntries(ctx context.Context, arg GetFrequentCalorieEntriesParams) ([]GetFrequentCalorieEntriesRow, error) {
	rows, err := q.db.Query(ctx, getFrequentCalorieEntries, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFrequentCalorieEntriesRow
	for rows.Next() {
		var i GetFrequentCalorieEntriesRow
		if err := rows.Scan(
			&i.Description,
			&i.Kcal,
			&i.TimesLogged,
			&i.LastLogged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCalorieDescriptions = `-- name: SearchCalorieDescriptions :many
SELECT DISTINCT description
FROM calories
WHERE user_id = $1 AND description ILIKE '%' || $2 || '%'
ORDER BY description
LIMIT $3
`

type SearchCalorieDescriptionsParams struct {
	UserID  int64
	Column2 pgtype.Text
	Limit   int32
}

func (q *Queries) SearchCalorieDescriptions(ctx context.Context, arg SearchCalorieDescriptionsParams) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, searchCalorieDescriptions, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var description pgtype.Text
		if err := rows.Scan(&description); err != nil {
			return nil, err
		}
		items = append(items, description)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
