// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercises.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (
    user_id, name
) VALUES (
    $1, $2
)
RETURNING id, user_id, name
`

type CreateExerciseParams struct {
	UserID int64
	Name   string
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createExercise, arg.UserID, arg.Name)
	var i Exercise
	err := row.Scan(&i.ID, &i.UserID, &i.Name)
	return i, err
}

const deleteExercise = `-- name: DeleteExercise :exec
DELETE FROM exercises WHERE id = $1 AND user_id = $2
`

type DeleteExerciseParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteExercise(ctx context.Context, arg DeleteExerciseParams) error {
	_, err := q.db.Exec(ctx, deleteExercise, arg.ID, arg.UserID)
	return err
}

const getExerciseByID = `-- name: GetExerciseByID :one
SELECT id, user_id, name FROM exercises
WHERE id = $1 AND user_id = $2
`

type GetExerciseByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetExerciseByID(ctx context.Context, arg GetExerciseByIDParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, getExerciseByID, arg.ID, arg.UserID)
	var i Exercise
	err := row.Scan(&i.ID, &i.UserID, &i.Name)
	return i, err
}

const getExerciseByName = `-- name: GetExerciseByName :one
SELECT id, user_id, name FROM exercises
WHERE user_id = $1 AND lower(name) = lower($2)
LIMIT 1
`

type GetExerciseByNameParams struct {
	UserID int64
	Lower  string
}

func (q *Queries) GetExerciseByName(ctx context.Context, arg GetExerciseByNameParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, getExerciseByName, arg.UserID, arg.Lower)
	var i Exercise
	err := row.Scan(&i.ID, &i.UserID, &i.Name)
	return i, err
}

const listExercises = `-- name: ListExercises :many
SELECT id, user_id, name FROM exercises
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListExercises(ctx context.Context, userID int64) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, listExercises, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(&i.ID, &i.UserID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchExercises = `-- name: SearchExercises :many
SELECT id, user_id, name FROM exercises
WHERE user_id = $1 AND name ILIKE '%' || $2 || '%'
ORDER BY name
LIMIT $3
`

type SearchExercisesParams struct {
	UserID  int64
	Column2 pgtype.Text
	Limit   int32
}

func (q *Queries) SearchExercises(ctx context.Context, arg SearchExercisesParams) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, searchExercises, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(&i.ID, &i.UserID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
