// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bodyweight struct {
	ID     int64
	UserID int64
	Date   pgtype.Date
	Kg     pgtype.Numeric
}

type Calorie struct {
	ID          int64
	UserID      int64
	Date        pgtype.Date
	Kcal        int32
	Description pgtype.Text
}

type Exercise struct {
	ID     int64
	UserID int64
	Name   string
}

type Routine struct {
	ID     int64
	UserID int64
	Name   string
}

type RoutineExercise struct {
	RoutineID  int64
	ExerciseID int64
}

type User struct {
	ID                    int64
	TelegramUserID        int64
	OnboardingCompleted   bool
	GeminiApiKeyEncrypted pgtype.Text
	CreatedAt             pgtype.Timestamptz
	HeightCm              pgtype.Numeric
	Gender                pgtype.Text
	Goal                  pgtype.Text
}

type WeeklySchedule struct {
	ID        int64
	UserID    int64
	DayOfWeek int16
	RoutineID pgtype.Int8
}

type Workout struct {
	ID         int64
	UserID     int64
	Date       pgtype.Date
	RoutineID  pgtype.Int8
	ExerciseID int64
	Weight     pgtype.Numeric
	Sets       int32
	Reps       int32
}
