// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routine_exercises.sql

package db

import (
	"context"
)

const addExerciseToRoutine = `-- name: AddExerciseToRoutine :exec
INSERT INTO routine_exercises (
    routine_id, exercise_id
) VALUES (
    $1, $2
)
ON CONFLICT DO NOTHING
`

type AddExerciseToRoutineParams struct {
	RoutineID  int64
	ExerciseID int64
}

func (q *Queries) AddExerciseToRoutine(ctx context.Context, arg AddExerciseToRoutineParams) error {
	_, err := q.db.Exec(ctx, addExerciseToRoutine, arg.RoutineID, arg.ExerciseID)
	return err
}

const getExercisesForRoutine = `-- name: GetExercisesForRoutine :many
SELECT e.id, e.user_id, e.name
FROM routine_exercises re
JOIN exercises e ON e.id = re.exercise_id
WHERE re.routine_id = $1
ORDER BY e.name
`

func (q *Queries) GetExercisesForRoutine(ctx context.Context, routineID int64) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, getExercisesForRoutine, routineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(&i.ID, &i.UserID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isExerciseInRoutine = `-- name: IsExerciseInRoutine :one
SELECT EXISTS (
    SELECT 1 FROM routine_exercises
    WHERE routine_id = $1 AND exercise_id = $2
) AS exists
`

type IsExerciseInRoutineParams struct {
	RoutineID  int64
	ExerciseID int64
}

func (q *Queries) IsExerciseInRoutine(ctx context.Context, arg IsExerciseInRoutineParams) (bool, error) {
	row := q.db.QueryRow(ctx, isExerciseInRoutine, arg.RoutineID, arg.ExerciseID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeExerciseFromRoutine = `-- name: RemoveExerciseFromRoutine :exec
DELETE FROM routine_exercises
WHERE routine_id = $1 AND exercise_id = $2
`

type RemoveExerciseFromRoutineParams struct {
	RoutineID  int64
	ExerciseID int64
}

func (q *Queries) RemoveExerciseFromRoutine(ctx context.Context, arg RemoveExerciseFromRoutineParams) error {
	_, err := q.db.Exec(ctx, removeExerciseFromRoutine, arg.RoutineID, arg.ExerciseID)
	return err
}
