// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routines.sql

package db

import (
	"context"
)

const createRoutine = `-- name: CreateRoutine :one
INSERT INTO routines (
    user_id, name
) VALUES (
    $1, $2
)
RETURNING id, user_id, name
`

type CreateRoutineParams struct {
	UserID int64
	Name   string
}

func (q *Queries) CreateRoutine(ctx context.Context, arg CreateRoutineParams) (Routine, error) {
	row := q.db.QueryRow(ctx, createRoutine, arg.UserID, arg.Name)
	var i Routine
	err := row.Scan(&i.ID, &i.UserID, &i.Name)
	return i, err
}

const deleteRoutine = `-- name: DeleteRoutine :exec
DELETE FROM routines WHERE id = $1 AND user_id = $2
`

type DeleteRoutineParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteRoutine(ctx context.Context, arg DeleteRoutineParams) error {
	_, err := q.db.Exec(ctx, deleteRoutine, arg.ID, arg.UserID)
	return err
}

const getRoutineByID = `-- name: GetRoutineByID :one
SELECT id, user_id, name FROM routines
WHERE id = $1 AND user_id = $2
`

type GetRoutineByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetRoutineByID(ctx context.Context, arg GetRoutineByIDParams) (Routine, error) {
	row := q.db.QueryRow(ctx, getRoutineByID, arg.ID, arg.UserID)
	var i Routine
	err := row.Scan(&i.ID, &i.UserID, &i.Name)
	return i, err
}

const getRoutineByName = `-- name: GetRoutineByName :one
SELECT id, user_id, name FROM routines
WHERE user_id = $1 AND lower(name) = lower($2)
LIMIT 1
`

type GetRoutineByNameParams struct {
	UserID int64
	Lower  string
}

func (q *Queries) GetRoutineByName(ctx context.Context, arg GetRoutineByNameParams) (Routine, error) {
	row := q.db.QueryRow(ctx, getRoutineByName, arg.UserID, arg.Lower)
	var i Routine
	err := row.Scan(&i.ID, &i.UserID, &i.Name)
	return i, err
}

const listRoutines = `-- name: ListRoutines :many
SELECT id, user_id, name FROM routines
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListRoutines(ctx context.Context, userID int64) ([]Routine, error) {
	rows, err := q.db.Query(ctx, listRoutines, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Routine
	for rows.Next() {
		var i Routine
		if err := rows.Scan(&i.ID, &i.UserID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
