// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAvgCaloriesForRange = `-- name: GetAvgCaloriesForRange :one
SELECT COALESCE(AVG(daily_total), 0)::numeric AS avg_kcal
FROM (
    SELECT date, SUM(kcal) AS daily_total
    FROM calories
    WHERE user_id = $1 AND date BETWEEN $2 AND $3
    GROUP BY date
) sub
`

type GetAvgCaloriesForRangeParams struct {
	UserID int64
	Date   pgtype.Date
	Date_2 pgtype.Date
}

func (q *Queries) GetAvgCaloriesForRange(ctx context.Context, arg GetAvgCaloriesForRangeParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getAvgCaloriesForRange, arg.UserID, arg.Date, arg.Date_2)
	var avg_kcal pgtype.Numeric
	err := row.Scan(&avg_kcal)
	return avg_kcal, err
}

const getAvgWeightForRange = `-- name: GetAvgWeightForRange :one
SELECT COALESCE(AVG(kg), 0)::numeric AS avg_kg
FROM bodyweight
WHERE user_id = $1 AND date BETWEEN $2 AND $3
`

type GetAvgWeightForRangeParams struct {
	UserID int64
	Date   pgtype.Date
	Date_2 pgtype.Date
}

func (q *Queries) GetAvgWeightForRange(ctx context.Context, arg GetAvgWeightForRangeParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getAvgWeightForRange, arg.UserID, arg.Date, arg.Date_2)
	var avg_kg pgtype.Numeric
	err := row.Scan(&avg_kg)
	return avg_kg, err
}

const getDailyCalorieTrend = `-- name: GetDailyCalorieTrend :many

SELECT date, SUM(kcal)::int AS total_kcal
FROM calories
WHERE user_id = $1 AND date >= $2
GROUP BY date
ORDER BY date
`

type GetDailyCalorieTrendParams struct {
	UserID int64
	Date   pgtype.Date
}

type GetDailyCalorieTrendRow struct {
	Date      pgtype.Date
	TotalKcal int32
}

// ===== Calorie trend =====
func (q *Queries) GetDailyCalorieTrend(ctx context.Context, arg GetDailyCalorieTrendParams) ([]GetDailyCalorieTrendRow, error) {
	rows, err := q.db.Query(ctx, getDailyCalorieTrend, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyCalorieTrendRow
	for rows.Next() {
		var i GetDailyCalorieTrendRow
		if err := rows.Scan(&i.Date, &i.TotalKcal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseSessionHistory = `-- name: GetExerciseSessionHistory :many

SELECT date, MAX(weight)::numeric AS max_weight, MAX(reps)::int AS max_reps
FROM workouts
WHERE user_id = $1 AND exercise_id = $2
GROUP BY date
ORDER BY date DESC
LIMIT $3
`

type GetExerciseSessionHistoryParams struct {
	UserID     int64
	ExerciseID int64
	Limit      int32
}

type GetExerciseSessionHistoryRow struct {
	Date      pgtype.Date
	MaxWeight pgtype.Numeric
	MaxReps   int32
}

// ===== Exercise progression / plateau detection =====
func (q *Queries) GetExerciseSessionHistory(ctx context.Context, arg GetExerciseSessionHistoryParams) ([]GetExerciseSessionHistoryRow, error) {
	rows, err := q.db.Query(ctx, getExerciseSessionHistory, arg.UserID, arg.ExerciseID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExerciseSessionHistoryRow
	for rows.Next() {
		var i GetExerciseSessionHistoryRow
		if err := rows.Scan(&i.Date, &i.MaxWeight, &i.MaxReps); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeightTrend = `-- name: GetWeightTrend :many

SELECT date, kg FROM bodyweight
WHERE user_id = $1 AND date >= $2
ORDER BY date
`

type GetWeightTrendParams struct {
	UserID int64
	Date   pgtype.Date
}

type GetWeightTrendRow struct {
	Date pgtype.Date
	Kg   pgtype.Numeric
}

// ===== Bodyweight trend =====
func (q *Queries) GetWeightTrend(ctx context.Context, arg GetWeightTrendParams) ([]GetWeightTrendRow, error) {
	rows, err := q.db.Query(ctx, getWeightTrend, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWeightTrendRow
	for rows.Next() {
		var i GetWeightTrendRow
		if err := rows.Scan(&i.Date, &i.Kg); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkoutFrequency = `-- name: GetWorkoutFrequency :one

SELECT COUNT(DISTINCT date)::int AS days_trained
FROM workouts
WHERE user_id = $1 AND date BETWEEN $2 AND $3
`

type GetWorkoutFrequencyParams struct {
	UserID int64
	Date   pgtype.Date
	Date_2 pgtype.Date
}

// ===== Workout consistency =====
func (q *Queries) GetWorkoutFrequency(ctx context.Context, arg GetWorkoutFrequencyParams) (int32, error) {
	row := q.db.QueryRow(ctx, getWorkoutFrequency, arg.UserID, arg.Date, arg.Date_2)
	var days_trained int32
	err := row.Scan(&days_trained)
	return days_trained, err
}
