// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
     telegram_user_id
) VALUES (
    $1
)
RETURNING id, telegram_user_id, onboarding_completed, gemini_api_key_encrypted, created_at, height_cm, gender, goal
`

func (q *Queries) CreateUser(ctx context.Context, telegramUserID int64) (User, error) {
	row := q.db.QueryRow(ctx, createUser, telegramUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.OnboardingCompleted,
		&i.GeminiApiKeyEncrypted,
		&i.CreatedAt,
		&i.HeightCm,
		&i.Gender,
		&i.Goal,
	)
	return i, err
}

const getUserByTelegramUserID = `-- name: GetUserByTelegramUserID :one
SELECT id, telegram_user_id, onboarding_completed, gemini_api_key_encrypted, created_at, height_cm, gender, goal FROM users WHERE telegram_user_id = $1 LIMIT 1
`

func (q *Queries) GetUserByTelegramUserID(ctx context.Context, telegramUserID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramUserID, telegramUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.OnboardingCompleted,
		&i.GeminiApiKeyEncrypted,
		&i.CreatedAt,
		&i.HeightCm,
		&i.Gender,
		&i.Goal,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT id, telegram_user_id, height_cm, gender, goal, onboarding_completed
FROM users
WHERE id = $1
`

type GetUserProfileRow struct {
	ID                  int64
	TelegramUserID      int64
	HeightCm            pgtype.Numeric
	Gender              pgtype.Text
	Goal                pgtype.Text
	OnboardingCompleted bool
}

func (q *Queries) GetUserProfile(ctx context.Context, id int64) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, id)
	var i GetUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.HeightCm,
		&i.Gender,
		&i.Goal,
		&i.OnboardingCompleted,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, telegram_user_id, onboarding_completed, gemini_api_key_encrypted, created_at, height_cm, gender, goal FROM users ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TelegramUserID,
			&i.OnboardingCompleted,
			&i.GeminiApiKeyEncrypted,
			&i.CreatedAt,
			&i.HeightCm,
			&i.Gender,
			&i.Goal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGender = `-- name: SetGender :one
UPDATE users SET gender = $2 WHERE id = $1 RETURNING id, telegram_user_id, onboarding_completed, gemini_api_key_encrypted, created_at, height_cm, gender, goal
`

type SetGenderParams struct {
	ID     int64
	Gender pgtype.Text
}

func (q *Queries) SetGender(ctx context.Context, arg SetGenderParams) (User, error) {
	row := q.db.QueryRow(ctx, setGender, arg.ID, arg.Gender)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.OnboardingCompleted,
		&i.GeminiApiKeyEncrypted,
		&i.CreatedAt,
		&i.HeightCm,
		&i.Gender,
		&i.Goal,
	)
	return i, err
}

const setGoal = `-- name: SetGoal :one
UPDATE users SET goal = $2 WHERE id = $1 RETURNING id, telegram_user_id, onboarding_completed, gemini_api_key_encrypted, created_at, height_cm, gender, goal
`

type SetGoalParams struct {
	ID   int64
	Goal pgtype.Text
}

func (q *Queries) SetGoal(ctx context.Context, arg SetGoalParams) (User, error) {
	row := q.db.QueryRow(ctx, setGoal, arg.ID, arg.Goal)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.OnboardingCompleted,
		&i.GeminiApiKeyEncrypted,
		&i.CreatedAt,
		&i.HeightCm,
		&i.Gender,
		&i.Goal,
	)
	return i, err
}

const setHeight = `-- name: SetHeight :one
UPDATE users SET height_cm = $2 WHERE id = $1 RETURNING id, telegram_user_id, onboarding_completed, gemini_api_key_encrypted, created_at, height_cm, gender, goal
`

type SetHeightParams struct {
	ID       int64
	HeightCm pgtype.Numeric
}

func (q *Queries) SetHeight(ctx context.Context, arg SetHeightParams) (User, error) {
	row := q.db.QueryRow(ctx, setHeight, arg.ID, arg.HeightCm)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.OnboardingCompleted,
		&i.GeminiApiKeyEncrypted,
		&i.CreatedAt,
		&i.HeightCm,
		&i.Gender,
		&i.Goal,
	)
	return i, err
}
