// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: weekly_schedule.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDaySchedule = `-- name: ClearDaySchedule :exec
DELETE FROM weekly_schedule WHERE user_id = $1 AND day_of_week = $2
`

type ClearDayScheduleParams struct {
	UserID    int64
	DayOfWeek int16
}

func (q *Queries) ClearDaySchedule(ctx context.Context, arg ClearDayScheduleParams) error {
	_, err := q.db.Exec(ctx, clearDaySchedule, arg.UserID, arg.DayOfWeek)
	return err
}

const getDaySchedule = `-- name: GetDaySchedule :one
SELECT id, user_id, day_of_week, routine_id FROM weekly_schedule
WHERE user_id = $1 AND day_of_week = $2
`

type GetDayScheduleParams struct {
	UserID    int64
	DayOfWeek int16
}

func (q *Queries) GetDaySchedule(ctx context.Context, arg GetDayScheduleParams) (WeeklySchedule, error) {
	row := q.db.QueryRow(ctx, getDaySchedule, arg.UserID, arg.DayOfWeek)
	var i WeeklySchedule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DayOfWeek,
		&i.RoutineID,
	)
	return i, err
}

const getFullWeekSchedule = `-- name: GetFullWeekSchedule :many
SELECT ws.day_of_week, r.id AS routine_id, r.name AS routine_name
FROM weekly_schedule ws
LEFT JOIN routines r ON r.id = ws.routine_id
WHERE ws.user_id = $1
ORDER BY ws.day_of_week
`

type GetFullWeekScheduleRow struct {
	DayOfWeek   int16
	RoutineID   pgtype.Int8
	RoutineName pgtype.Text
}

func (q *Queries) GetFullWeekSchedule(ctx context.Context, userID int64) ([]GetFullWeekScheduleRow, error) {
	rows, err := q.db.Query(ctx, getFullWeekSchedule, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFullWeekScheduleRow
	for rows.Next() {
		var i GetFullWeekScheduleRow
		if err := rows.Scan(&i.DayOfWeek, &i.RoutineID, &i.RoutineName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDaySchedule = `-- name: SetDaySchedule :one
INSERT INTO weekly_schedule (
    user_id, day_of_week, routine_id
) VALUES (
    $1, $2, $3
)
ON CONFLICT (user_id, day_of_week)
DO UPDATE SET routine_id = EXCLUDED.routine_id
RETURNING id, user_id, day_of_week, routine_id
`

type SetDayScheduleParams struct {
	UserID    int64
	DayOfWeek int16
	RoutineID pgtype.Int8
}

func (q *Queries) SetDaySchedule(ctx context.Context, arg SetDayScheduleParams) (WeeklySchedule, error) {
	row := q.db.QueryRow(ctx, setDaySchedule, arg.UserID, arg.DayOfWeek, arg.RoutineID)
	var i WeeklySchedule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DayOfWeek,
		&i.RoutineID,
	)
	return i, err
}
