// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workouts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteWorkout = `-- name: DeleteWorkout :exec
DELETE FROM workouts WHERE id = $1 AND user_id = $2
`

type DeleteWorkoutParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteWorkout(ctx context.Context, arg DeleteWorkoutParams) error {
	_, err := q.db.Exec(ctx, deleteWorkout, arg.ID, arg.UserID)
	return err
}

const getHistoryForExercise = `-- name: GetHistoryForExercise :many
SELECT id, user_id, date, routine_id, exercise_id, weight, sets, reps FROM workouts
WHERE user_id = $1 AND exercise_id = $2
ORDER BY date DESC, id DESC
LIMIT $3
`

type GetHistoryForExerciseParams struct {
	UserID     int64
	ExerciseID int64
	Limit      int32
}

func (q *Queries) GetHistoryForExercise(ctx context.Context, arg GetHistoryForExerciseParams) ([]Workout, error) {
	rows, err := q.db.Query(ctx, getHistoryForExercise, arg.UserID, arg.ExerciseID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.RoutineID,
			&i.ExerciseID,
			&i.Weight,
			&i.Sets,
			&i.Reps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPersonalBest = `-- name: GetPersonalBest :one
SELECT id, user_id, date, routine_id, exercise_id, weight, sets, reps FROM workouts
WHERE user_id = $1 AND exercise_id = $2
ORDER BY weight DESC, reps DESC
LIMIT 1
`

type GetPersonalBestParams struct {
	UserID     int64
	ExerciseID int64
}

func (q *Queries) GetPersonalBest(ctx context.Context, arg GetPersonalBestParams) (Workout, error) {
	row := q.db.QueryRow(ctx, getPersonalBest, arg.UserID, arg.ExerciseID)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.RoutineID,
		&i.ExerciseID,
		&i.Weight,
		&i.Sets,
		&i.Reps,
	)
	return i, err
}

const getWorkoutByID = `-- name: GetWorkoutByID :one
SELECT id, user_id, date, routine_id, exercise_id, weight, sets, reps FROM workouts
WHERE id = $1 AND user_id = $2
`

type GetWorkoutByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetWorkoutByID(ctx context.Context, arg GetWorkoutByIDParams) (Workout, error) {
	row := q.db.QueryRow(ctx, getWorkoutByID, arg.ID, arg.UserID)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.RoutineID,
		&i.ExerciseID,
		&i.Weight,
		&i.Sets,
		&i.Reps,
	)
	return i, err
}

const getWorkoutsByDateRange = `-- name: GetWorkoutsByDateRange :many
SELECT w.id, w.user_id, w.date, w.routine_id, w.exercise_id, w.weight, w.sets, w.reps, e.name AS exercise_name
FROM workouts w
JOIN exercises e ON e.id = w.exercise_id
WHERE w.user_id = $1 AND w.date BETWEEN $2 AND $3
ORDER BY w.date, w.id
`

type GetWorkoutsByDateRangeParams struct {
	UserID int64
	Date   pgtype.Date
	Date_2 pgtype.Date
}

type GetWorkoutsByDateRangeRow struct {
	ID           int64
	UserID       int64
	Date         pgtype.Date
	RoutineID    pgtype.Int8
	ExerciseID   int64
	Weight       pgtype.Numeric
	Sets         int32
	Reps         int32
	ExerciseName string
}

func (q *Queries) GetWorkoutsByDateRange(ctx context.Context, arg GetWorkoutsByDateRangeParams) ([]GetWorkoutsByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, getWorkoutsByDateRange, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkoutsByDateRangeRow
	for rows.Next() {
		var i GetWorkoutsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.RoutineID,
			&i.ExerciseID,
			&i.Weight,
			&i.Sets,
			&i.Reps,
			&i.ExerciseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkoutsForDate = `-- name: GetWorkoutsForDate :many
SELECT w.id, w.user_id, w.date, w.routine_id, w.exercise_id, w.weight, w.sets, w.reps, e.name AS exercise_name
FROM workouts w
JOIN exercises e ON e.id = w.exercise_id
WHERE w.user_id = $1 AND w.date = $2
ORDER BY w.id
`

type GetWorkoutsForDateParams struct {
	UserID int64
	Date   pgtype.Date
}

type GetWorkoutsForDateRow struct {
	ID           int64
	UserID       int64
	Date         pgtype.Date
	RoutineID    pgtype.Int8
	ExerciseID   int64
	Weight       pgtype.Numeric
	Sets         int32
	Reps         int32
	ExerciseName string
}

func (q *Queries) GetWorkoutsForDate(ctx context.Context, arg GetWorkoutsForDateParams) ([]GetWorkoutsForDateRow, error) {
	rows, err := q.db.Query(ctx, getWorkoutsForDate, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkoutsForDateRow
	for rows.Next() {
		var i GetWorkoutsForDateRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.RoutineID,
			&i.ExerciseID,
			&i.Weight,
			&i.Sets,
			&i.Reps,
			&i.ExerciseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logWorkout = `-- name: LogWorkout :one
INSERT INTO workouts (
    user_id, date, routine_id, exercise_id, weight, sets, reps
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, date, routine_id, exercise_id, weight, sets, reps
`

type LogWorkoutParams struct {
	UserID     int64
	Date       pgtype.Date
	RoutineID  pgtype.Int8
	ExerciseID int64
	Weight     pgtype.Numeric
	Sets       int32
	Reps       int32
}

func (q *Queries) LogWorkout(ctx context.Context, arg LogWorkoutParams) (Workout, error) {
	row := q.db.QueryRow(ctx, logWorkout,
		arg.UserID,
		arg.Date,
		arg.RoutineID,
		arg.ExerciseID,
		arg.Weight,
		arg.Sets,
		arg.Reps,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.RoutineID,
		&i.ExerciseID,
		&i.Weight,
		&i.Sets,
		&i.Reps,
	)
	return i, err
}
